# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  #config.vm.box = 'bento/ubuntu-18.10'
  config.vm.box = 'centos/7'
  
  config.vm.synced_folder '..', '/solita.jenkins',
    owner: 'vagrant',
    group: 'vagrant',
    type: 'rsync',
    rsync__exclude: '.git/'
  config.vm.network :forwarded_port, guest: 8081, host: 9080

  config.vm.provider 'virtualbox' do |v|
    v.memory = 1024
  end

  config.vm.provision 'shell', privileged: false, inline: <<-EOF
    set -e

    # Install Ansible - Ubuntu
    #sudo apt update
    #sudo apt install -y software-properties-common
    #sudo apt-add-repository ppa:ansible/ansible -y
    #sudo apt update
    #sudo apt install -y ansible
    
    # Install Ansible - Centos
    sudo yum update -y
    sudo yum install epel-release -y
    sudo yum install ansible -y

    # Start new login shells in the /solita.jenkins/test directory
    echo 'cd /solita.jenkins/test' >> ~/.profile

    # Install role dependencies
    cd /solita.jenkins/test
    bash install-dependencies.sh

    # Perform a basic installation of the role (assumed by the tests)
    export PYTHONUNBUFFERED=1
    ansible-galaxy -r requirements.yml install
    ansible-playbook -i environments/vagrant/inventory site.yml
  EOF
end
